### ISSUE TITLE
Modpack keeps restarting

### ISSUE THREAD

**Issue by AzzaBGitHubories** [The-1-7-10-Pack/The-1.7.10-Pack#574] opened 2015-05-15 19:37 UTC
Hiya,

I'm not sure if this is a pack problem or another problem but my server seems to restart itself randomly for no reason after very short uptime (10 minutes for example) with even no one on the server?... is this a host issue or a pack issue?

Thank you!

Aaron

**Comment by The-1-7-10-Pack** [comment] 2015-05-16 17:45
Duplicate of #568. Please post your latest server log there to give me more information. Please use a [paste-tool](http://paste.ubuntu.com/).

**Closed by The-1-7-10-Pack** 2015-05-16 17:45 UTC
Labels: duplicate
