### ISSUE TITLE
1.7.10 server pack does not work

### ISSUE THREAD

**Issue by TreeMarie84** [The-1-7-10-Pack/The-1.7.10-Pack#102] opened 2015-01-24 19:20 UTC
I've downloaded the server pack for this mod. Uploaded it through Filezilla. Contacted Full Effect hosting and they say the problem is with the server pack.

My problem is the mods do not work in multiplayer. However they work fine in singleplayer. I've tried manually installing Tinkers since Tinkers shows in the modpack inventory but is not in the mod list in the server files.

I'd like to know why all of the mods aren't working.

**Comment by The-1-7-10-Pack** [comment] 2015-01-24 19:23
"they say the problem is with the server pack"
Did you look up how to report a bug here?: https://github.com/The-1-7-10-Pack/The-1.7.10-Pack
Please provide more information: Crash report, latest server log, somethin'.

**Comment by TreeMarie84** [comment] 2015-01-24 20:31
There is no crash report as the modpack loads fine. It loads it as Vanilla with no mods working. Anything I click on for a tekkit mod says "No such item found item number ###"

I found this link from the tekkit mod download page, led me here

**Comment by The-1-7-10-Pack** [comment] 2015-01-24 21:12
You need support for Tekkit or for The 1.7.10 Pack?

**Comment by TreeMarie84** [comment] 2015-01-24 21:14
1.7.10 pack please

**Comment by The-1-7-10-Pack** [comment] 2015-01-24 21:39
Okay.
So the hosting company told you that they have a problem?

**Comment by Flukethoughts** [comment] 2015-01-24 21:40
ok I need to know what kinda server hosting it is for instance what is the control panel?

**Comment by TreeMarie84** [comment] 2015-01-24 22:16
Full Effect Hosting, they said the server was fine. That it was a problem with the modpack.

**Comment by Flukethoughts** [comment] 2015-01-24 22:22
I understand that but what control panel and how is it set up. Because I can honestly say most server hosting companies don't know anything

**Comment by TreeMarie84** [comment] 2015-01-24 22:31
Lol tell me about it. Would you like a screenshot?

**Comment by TreeMarie84** [comment] 2015-01-24 23:22
I believe it's Multicraft, if you need a screenshot of the control panel let me know

**Comment by Flukethoughts** [comment] 2015-01-25 02:28
Have you moved the library and minecraftserver jar and forgeserver jar to the jar directory?

**Comment by TreeMarie84** [comment] 2015-01-25 02:30
The only thing I did was downloaded your server pack, and uploaded it through FileZilla and renamed the .jar to custom.jar

**Comment by Flukethoughts** [comment] 2015-01-25 02:30
call me on skype not_just_a_fluke

**Comment by The-1-7-10-Pack** [comment] 2015-01-30 12:38
Closing this one.

**Closed by The-1-7-10-Pack** 2015-01-30 12:38 UTC
Labels: help wanted, missing information
