### ISSUE TITLE
Minecraft not launching

### ISSUE THREAD

**Issue by xxOmNiMoNxx** [The-1-7-10-Pack/The-1.7.10-Pack#771] opened 2015-07-23 03:17 UTC
When i launch the pack minecraft opens but it stays as a black screen and never loads. my java is at 4gb and everything else is fine

**Comment by skittishtrigger** [comment] 2015-07-23 03:28
Hmm, I would post some logs so there is some info to go off of. use pastebin or http://paste.ubuntu.com so they can see whats going on. BUT it might be tied to mojangs ddos attack recently so a lot of servers are down anyways.

**Comment by TheUnknownVariable** [comment] 2015-07-24 00:35
the "attack" was on the multiplayer server. It had nothing to do with authentication and he could've still played online. It might be an issue with Java. Try reinstalling it or updating it if you have not done so already

**Comment by skittishtrigger** [comment] 2015-07-24 03:35
?Must have  been a separate attack because mojangs auth servers (as well as most of their others on/off again) were down for about 11hours. And without further information it could be a lot of things being a black screen. the client logs inside the .technic/modpacks/The-1.7.10-Pack would be very helpful. Hopefully there is a response so the guys can close it if the issue is resolved.

**Comment by The-1-7-10-Pack** [comment] 2015-07-26 14:06
Closed due to missing information.

**Closed by The-1-7-10-Pack** 2015-07-26 14:06 UTC
Labels: help wanted, missing information
