### ISSUE TITLE
Modpack not opening

### ISSUE THREAD

**Issue by shanwker1223** [The-1-7-10-Pack/The-1.7.10-Pack#605] opened 2015-05-25 06:27 UTC
After the 0.7.7 update it is not opening anymore, i've tried to reinstall, uninstall and install alot of versions, but 0.7.7 is not working.
Log(Sorry, just created account to post this, don't know how to use github):
**EDITED: Please use a paste-tool: http://pastebin.com/GtF8jyYh**

**Comment by The-1-7-10-Pack** [comment] 2015-05-25 09:45
This is not the full log. Please post the **full** log and use a [paste-tool](http://paste.ubuntu.com/)!

**Comment by The-1-7-10-Pack** [comment] 2015-05-25 09:49
Go to your mods folder. Try to delete the Thaumic Tinkerer mod, and replace it with [this](http://minecraft.curseforge.com/mc-mods/75598-thaumic-tinkerer/files/2232793) version of the mod. Does it launch?

**Comment by shanwker1223** [comment] 2015-05-25 13:25
No, it didn't launch, and it gave me the same log

**Comment by The-1-7-10-Pack** [comment] 2015-05-25 14:09
- Were you able to launch with v0.7.6c of the pack?
- Try to replace it with [this](http://jenkins.nekokittygames.com:8080/job/Thaumic%20Tinkerer/474/) version, does it launch?

**Comment by TheLegend714** [comment] 2015-05-25 14:16
The problem may be java 8.

**Comment by shanwker1223** [comment] 2015-05-25 14:25
Yes, i used the recommended 0.7.6 and it launched normally
It still didn't work

**Comment by TheLegend714** [comment] 2015-05-25 14:32
7.7b is now recommended lol

**Comment by shanwker1223** [comment] 2015-05-25 14:38
I know... but when i installed it was 0.7.6

**Comment by The-1-7-10-Pack** [comment] 2015-05-25 14:42
@shanwker1223 Does the version I just gave you work? Are you able to launch the client with this version of the mod?

**Comment by shanwker1223** [comment] 2015-05-25 14:55
Yes, and still the same issue.
http://pastebin.com/5rK24PPG
The log, if it helps.

**Comment by TheLegend714** [comment] 2015-05-25 15:02
Should we stick with 7.6c?

**Comment by The-1-7-10-Pack** [comment] 2015-05-25 15:43
@shanwker1223 That's nonsense, as v0.7.6c runs with build 474 of Thaumic Tinkerer. Also I can't reproduce this myself.

**Comment by TheLegend714** [comment] 2015-05-25 16:14
Weird it works on 7.6c for me?

**Comment by The-1-7-10-Pack** [comment] 2015-05-25 16:40
@TheLegend714 Are you able to launch v0.7.7b okay?

**Comment by The-1-7-10-Pack** [comment] 2015-05-25 16:48
Well guys I see that it's a problem with the mod that occurs on other modpacks too. It's a mod-bug and there's nothing I can do, The 1.7.10 Pack uses the latest version of Thaumic Tinkerer. For now you can manually remove the mod and it should work. Also try to get help in the issues page of Thaumic Tinkerer. Closing this for now.

**Closed by The-1-7-10-Pack** 2015-05-25 16:48 UTC
Labels: can't reproduce, help wanted

**Comment by TheLegend714** [comment] 2015-05-25 16:51
Nope

**Comment by The-1-7-10-Pack** [comment] 2015-05-25 16:52
@TheLegend714 Nope-what?

**Comment by TheLegend714** [comment] 2015-05-25 16:53
7.7b wont load also when i removed thaumic tinkerer i don't think it changed ill try again.

**Comment by TheLegend714** [comment] 2015-05-25 16:57
Well it seems removing thaumic tinkerer dint make a difference???

**Comment by The-1-7-10-Pack** [comment] 2015-05-25 17:02
@TheLegend714 Please give your latest client log after you've removed the Thaumic Tinkerer mod and you're not able to launch.

**Comment by TheLegend714** [comment] 2015-05-25 17:02
aight

**Comment by TheLegend714** [comment] 2015-05-25 17:03
http://paste.ubuntu.com/11353403/       FML

**Comment by TheLegend714** [comment] 2015-05-25 17:06
Question if i ever get the mudpack to work latest version can i import my save to the new version?

**Comment by The-1-7-10-Pack** [comment] 2015-05-25 17:09
@TheLegend714 Yes.

**Comment by TheLegend714** [comment] 2015-05-25 17:09
Cool

**Comment by TheLegend714** [comment] 2015-05-25 17:24
My log http://paste.ubuntu.com/11353403/

**Comment by The-1-7-10-Pack** [comment] 2015-05-25 17:48
Basically it's a problem that is related maybe to the Forge version, or some other mod version, with another specific thing in your system. May be the guava version, I'm really not sure.

**Comment by TheLegend714** [comment] 2015-05-25 17:56
Can you link me java 7 then?

**Comment by TheLegend714** [comment] 2015-05-25 17:59
Ill just wait until the next update comes for your modpack thanks for trying to help ;)

**Comment by The-1-7-10-Pack** [comment] 2015-05-25 19:20
@TheLegend714 Anyway I suspect it's a libaries problem. You can try to reinstall the launcher, which will reinstall the libaries. It might help. Same for you, @shanwker1223.

**Comment by TheLegend714** [comment] 2015-05-25 20:03
I'll try

**Comment by shanwker1223** [comment] 2015-05-26 02:01
I'll try too, thanks

**Comment by The-1-7-10-Pack** [comment] 2015-05-26 07:42
@TheLegend714 & @shanwker1223 Did it help?

**Comment by bochen415** [comment] 2015-05-26 08:00
For testing purposes the *cache* directory inside the *.technic* directory should be deleted as it contains the libraries in question.
It's a good practice to make a backup of the entire .technic directory beforehand.

**Comment by TheLegend714** [comment] 2015-05-26 13:19
Trying it today.
