### ISSUE TITLE
Download Error 

### ISSUE THREAD

**Issue by abbikate** [The-1-7-10-Pack/The-1.7.10-Pack#592] opened 2015-05-22 16:18 UTC
Hi, 

Trying to download and play this modpack through the technic launcher.  I've tried on two separate windows 8 computers and get exactly the same error. 

The pack seems to download ok but comes with the following error when I hit 'play'. 

"CB's DepLoader was unable to download required library vorbis-java-core-0.8-20150201.161816-1.jar Check your internet connection and try restarting or download it manually from (link to said java-core) and put it in your mods folder" 

I'm running the latest java 64 bit, all of my other technic modpacks work including some new ones.  I've tried following the link and it seems broken or something. 

Thanks in advance for your help! 

:)

**Comment by RivalSpirit** [comment] 2015-05-22 16:48
I have the same problem. I have been playing this modpack for awhile and this problem just started today. I am also running the latest java and I tried to play the latest version of the modpack. I don't know If  the fact I'm using a mac makes a difference.
Also, you should put up the crash report.

**Comment by RivalSpirit** [comment] 2015-05-22 16:50
My crash report:
http://paste.ubuntu.com/11288308/

**Comment by oryfoxer7410** [comment] 2015-05-24 03:53
duplicate of  #591

**Closed** 2015-05-24 18:16 UTC
Labels: duplicate
