### ISSUE TITLE
Not Loading Game!

### ISSUE THREAD

**Issue by mmooll** [The-1-7-10-Pack/The-1.7.10-Pack#368] opened 2015-03-20 03:21 UTC
Please help me I really want to play your modpack but I can not.  I have 7 java 64-bit.  Please help!

**Comment by The-1-7-10-Pack** [comment] 2015-03-20 09:43
Please provide the latest launcher log (:

**Comment by The-1-7-10-Pack** [comment] 2015-03-21 20:32
Closed due to missing information.

**Comment by mmooll** [comment] 2015-03-22 01:58
Please help
How do I show you?

**Comment by mmooll** [comment] 2015-03-22 01:58
Or where do I show you?

**Comment by mmooll** [comment] 2015-03-22 02:03
Please re-open the thing! Please!  It was working with version 10.7.0 but when I updated to 10.7.5 it stopped working again.

**Comment by mmooll** [comment] 2015-03-22 02:15
I am sorry I meant 0.7.5

**Comment by The-1-7-10-Pack** [comment] 2015-03-22 14:54
I need your latest launcher log.
Open the Technic Launhcer and click on the "Launcher Options", then click "Open Logs" And give me the latest log. Please use a [paste-tool](http://paste.ubuntu.com/).

**Comment by mmooll** [comment] 2015-03-22 16:35
Thank you for responding here is my log. http://paste.ubuntu.com/10653151/  Please tell me if that is the right log because I gave the latest but there were to places where I could get the log from a .zip or .log I opened the .zip and copied it in to ubuntu.  Thank you.

**Comment by The-1-7-10-Pack** [comment] 2015-03-22 17:11
This is the wrong log, I've asked for the launcher log and not the client log :P
The launcher log is located under "AppData\Roaming\.technic\logs".

**Comment by mmooll** [comment] 2015-03-22 17:12
I have a mac so where would I go?

**Comment by mmooll** [comment] 2015-03-22 17:15
Never mind here is this the right thing? http://paste.ubuntu.com/10653523/

**Comment by The-1-7-10-Pack** [comment] 2015-03-22 17:54
It looks like it's loading, what exactly is happening?

**Comment by mmooll** [comment] 2015-03-22 18:34
Ya the modpack loads up until it says initializing and then it just closes.  It is on the screen with the hour glass.  It is almost done and then it closes I really have no idea why?

**Comment by The-1-7-10-Pack** [comment] 2015-03-22 21:02
Closes? You need to let it load :P

**Comment by mmooll** [comment] 2015-03-23 00:45
I let it load but it closes by itself.  Would you like me to send you a video?

**Comment by The-1-7-10-Pack** [comment] 2015-03-23 10:08
It will help!

**Comment by mmooll** [comment] 2015-03-23 21:04
Ok here is the video.  This is raw copy nothing has been changed. I did not close out of it I did nothing to it.  https://vimeo.com/123025202  Sorry I could not fit it in the github.  Anyway the password is: help
Thanks.

**Comment by The-1-7-10-Pack** [comment] 2015-03-24 13:22
Okay..intresting.
It's really weird and it shouldn't happen. It's just normally loading and then something closes it.

**Comment by tlrg** [comment] 2015-03-24 13:43
I have the exact same problem. It just doesn't star up. It loads and then it malfunctions and shuts off.
Help please!!! Really wan't to play the pack!! T-T

**Comment by The-1-7-10-Pack** [comment] 2015-03-24 17:54
How much RAM do you have guys?

**Comment by grlinko115** [comment] 2015-03-24 22:11
I have 8GB of RAM and mine is doing the same things. I can almost guarantee you that the problem is because we most likely all have macs or OSX operating system. It is most likely java but im not sure which version we need.

**Comment by TheJanissaire** [comment] 2015-03-24 23:00
That not because you have a MAC,i have Windows 8.1 and an asus G75V,and,i still have this bug...3.4ghz,16 gb RAM.

**Comment by grlinko115** [comment] 2015-03-24 23:18
Also all other modpacks work fine.

**Comment by TheJanissaire** [comment] 2015-03-24 23:23
Yo peeps,actualy,it's java.

Use the most recent java x64 version.

And,that will work.

**Comment by grlinko115** [comment] 2015-03-24 23:28
which java version are you running?

**Comment by mmooll** [comment] 2015-03-25 00:26
Yeah what is the latest version of java that you are using because I am using the most recent java on my computer.  Here is what it reads. Latest 64-bit (1.7.0_25 64-bit) I am really confused and at a lose of solutions.

**Comment by grlinko115** [comment] 2015-03-25 00:31
Okay so i deleted Java 8 and installed Java 7 to see if that worked and that did nothing. So there must either be a specific version of java we need or its something unrelated.

**Comment by The-1-7-10-Pack** [comment] 2015-03-25 12:56
You guys should check the Java version that the launcher is using

**Comment by The-1-7-10-Pack** [comment] 2015-03-25 13:01
@mmooll, @tlrg, @grlinko115, @TheJanissaire: As I see on mmooll's log, there's this error:
> java.net.URISyntaxException: Illegal character in path at index 42: file:///Users/DrPepper/Library/Application Support/technic/logs/

The illegal character is the space in the "Application Support". Your Java version doesn't like it.
You can either update java, latest version of Java is "Java 8 update 40", or do something about this broken path.

This is the problem, so I'm closing this one for now so people won't get confused.

**Closed by The-1-7-10-Pack** 2015-03-25 13:01 UTC
Labels: help wanted

**Comment by grlinko115** [comment] 2015-03-25 13:32
I have Java 8 update 40 and it does not work after trying multiple things. How would one fix the broken path?

**Comment by The-1-7-10-Pack** [comment] 2015-03-25 13:49
Before that, can you please check on the launcher -> settings -> java settings and see you're indeed using this Java version?

**Comment by TheJanissaire** [comment] 2015-03-25 15:51
Delete the older java version,use the java website.

After,download the most recent x64 java,turn off internet,and,all other application.


Install it.

Run the launcher as a administrator.

Enjoy your game.

**Comment by grlinko115** [comment] 2015-03-25 15:53
Okay it says im using Latest 64 Bit (1.7.0_06 64-Bit). I have installed Java 8 u40. How do we run it is an administrator.

**Comment by The-1-7-10-Pack** [comment] 2015-03-25 17:55
Just uninstall the other Java versions and check you're using Java 8 Update 40. No real need to run the launcher as a administrator :P

**Comment by grlinko115** [comment] 2015-03-25 18:25
The only Java I have installed on my computer is Java 8 update 40. Unless you mean the Java for the launcher, in that case how would I go about doing that?

**Comment by mmooll** [comment] 2015-03-25 21:28
What do I do to make it work rename my application support folder or do something else I have no idea what to do!?

**Comment by The-1-7-10-Pack** [comment] 2015-03-25 21:43
@mmooll @grlinko115 You can try to remove the space in the "Application Support" Folder, although I'm not sure it's the best thing to do. You can also try to move the place where the Technic Launcher is installed.

**Comment by mmooll** [comment] 2015-03-25 22:28
It will not let me change the name of the folder.  Also it will not let me move the technic folder anywhere else

**Comment by grlinko115** [comment] 2015-03-25 23:17
It has to be something with this specific modpack though because all other modpacks work. i.e. B team, Hexxit, ect.

**Comment by mmooll** [comment] 2015-03-26 00:45
The modpack if finally working.  I can confirm that it was the space in the folder's name.  I moved to another directory and it worked.  Thank you for the help!

**Comment by The-1-7-10-Pack** [comment] 2015-03-26 04:51
:)
