### ISSUE TITLE
Game crashes on creative search tab use

### ISSUE THREAD

**Issue by paytengames** [The-1-7-10-Pack/The-1.7.10-Pack#112] opened 2015-01-26 03:47 UTC
**You need to use a paste-tool: http://paste.ubuntu.com/9878452**

**Comment by Flukethoughts** [comment] 2015-01-26 04:16
hey make this on a paste tool or i will close the issue sorry follow rules or receive no help

**Comment by The-1-7-10-Pack** [comment] 2015-01-26 08:16
I was not  able to reproduce this, what item did you searched? when did it happen exactly?

**Comment by thebalck** [comment] 2015-01-26 10:08
This happens to me too when im in creative if i click in the compass in inventory the game crashes

**Comment by The-1-7-10-Pack** [comment] 2015-01-26 10:55
Can you provide information about systems?

**Comment by paytengames** [comment] 2015-01-26 14:55
Systems like my computer? If so then: http://puu.sh/f3lY7/e56dbc5c29.png

Otherwise I'm not sure what you're asking for. And it occurs whenever I either: click the search tab or the navigate to the 13th tab of mods in the creative inventory.

**Comment by Flukethoughts** [comment] 2015-01-26 18:44
no it's the modpack. modpack wont let anyone use creative while on the server

**Comment by The-1-7-10-Pack** [comment] 2015-01-26 18:47
It's not a critical bug, lol.
Anyway, please report this issue there: https://github.com/BuildCraft/BuildCraft/issues
I'm pretty sure it's because of buildcraft. Be sure to mention there that it's client side only, and give them the crash report.

**Comment by The-1-7-10-Pack** [comment] 2015-02-01 15:28
I'll keep it open until I update the pack, so I'll remember.

**Closed** 2015-02-02 08:42 UTC
Labels: #don't_blame_the_modpack, bug, server side only

**Comment by thebalck** [comment] 2015-02-03 22:12
Men i dont know what happen but i can use the search tab now : D

**Comment by The-1-7-10-Pack** [comment] 2015-02-04 15:53
Black magic?

**Comment by thebalck** [comment] 2015-02-04 17:54
Maybe xD
