### ISSUE TITLE
Random chunk causing client freezing

### ISSUE THREAD

**Issue by Dommain** [The-1-7-10-Pack/The-1.7.10-Pack#416] opened 2015-03-30 16:55 UTC
After the recent update, I could not login because of the mechanism bug. I updated to the alpha version and I noticed I could not go near a certain group of chunks. It would freeze but not crash my game but not crash. I would use the 2-chunk distance to move away from the chunk but today I accidentally moved to close to the chunk in question and it crashed under the 2-chunk distance render. The crash log is bellow.

http://pastebin.com/iWcD5w9c

**Comment by Dommain** [comment] 2015-03-30 17:31
Crash upon loading the game in said chunk area. You can see entities and chunks start to load before crashing.

http://pastebin.com/YBNVGqFS

**Comment by The-1-7-10-Pack** [comment] 2015-03-30 18:08
Duplicate of #414, but you can really help there too. Please try the steps there one by one and see if anyone of them helps.

**Closed by The-1-7-10-Pack** 2015-03-30 18:08 UTC
Labels: duplicate
