### ISSUE TITLE
Modular Power Suits bugged: Crash when creating items and no recipes shown with NEI on a server

### ISSUE THREAD

**Issue by renescamen** [The-1-7-10-Pack/The-1.7.10-Pack#208] opened 2015-02-18 01:22 UTC
After I crafted the body armor from modular suits I have been crashing on start up of my world. Can't even play

**Comment by The-1-7-10-Pack** [comment] 2015-02-18 12:51
Please read how to report a bug [here](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack).

**Comment by The-1-7-10-Pack** [comment] 2015-02-19 14:22
http://www.technicpack.net/status/86392

**Comment by joelou1** [comment] 2015-02-19 16:50
Modular Powersuit is a very powerfull tool. I wanted to create a full set in order to roll. I've noticed that the recipe did not showed up on NEI or on the crafting table. (Reading on Technicpack deleting a certain folder would work.) Once deleted the recipe would show, I believe it did not last long though.
(This ain't part of this bug, but could be strongly related)

Now the important thing. I've then created the bodysuit and then the Leggings. When the leggings are finally placed in my inventory, game crashes. I've tested the Issue different ways, crafting it and putting it in the Tool bar, the inventory and even dropped it on the floor to pick it up. As soon as my character have it in it's inventory, the server can't read my character anymore, luckily, we could save my character and remove the unwanted object using InvEdit, but remains the bug that causes the armor to NOT be craftable.

Tests led me to try NEI to get it. Getting it from NEI does not crash my game.

Here's a link to what I think is the crash report: http://paste.ubuntu.com/10310329/


And here's a picture from the bug of the recipe. (Applying to all recipes from this mod)

![image](https://cloud.githubusercontent.com/assets/1740156/6271213/35311be4-b82d-11e4-92ce-750ef3ad9fee.png)

**Comment by The-1-7-10-Pack** [comment] 2015-02-19 16:54
@joelou1 Does this all happened on a server?

**Comment by joelou1** [comment] 2015-02-19 17:01
Sorry, tons of info, not clear enough. My bad.

Bug list:
- On server, recipes for crafting items from Modular Powersuits does not appear neither in NEI or in the crafting table (But still able to craft it because the sprite is simply invisible)
- On server AND single player: Crafting Leggings from the Powersuit causes a crash and causes the character to be unsuable unless the item is removed via external sources.

Sorry for the rush of information.

**Comment by The-1-7-10-Pack** [comment] 2015-02-19 17:10
@joelou1 Much better. Can you please reset (delete) the same folder that I told to in client now in server?

**Comment by joelou1** [comment] 2015-02-19 17:34
I'll do again then.

Steps:
1. Closed MC
2. Closed Server
3. Removed MachineMuse configs on Client and Server
4. Reopenning MC and Server
5. Test out both bugs.

Results: 
- MachineMuse Configs has been deleted and recreated. 
- Client crashes upon creating leggings. (Tested on Single and Multi-player)
- Recipe is still unavailable on server (NEI and Crafting Table), but can still be crafted(invisible sprite) and is visible only in Single-player.

Thank you.

**Comment by The-1-7-10-Pack** [comment] 2015-02-19 18:36
I checked and confirmed both bugs. I also checked and both bugs already have been reported.
I hope that it will get fixed soon, unfortunately nothing I can do about it.
Do you guys thing I should update the pack and remove MPS, or should I wait until it updates and fixed both bugs?

**Comment by joelou1** [comment] 2015-02-19 18:41
The Crafting Recipe bug is there since a GOOD while (therefore is minor and might not be fixed soon as modular powersuit is a 1.6.4 mod). The other bug is way more major as the only way to obtain is by NEI spawning. I'd rather wait until this bug is fixed before adding this mod. I'd agree to the removal.

**Comment by The-1-7-10-Pack** [comment] 2015-02-19 18:47
@joelou1 The thing is, that maybe until I'll get the update out the mod will update and you'll want to add it again. Thus, we'll have to make 2 updates. We can skip this process and just wait a bit more.

**Comment by joelou1** [comment] 2015-02-19 18:49
Ok. It's fine with me, as long as it's playable in the end. We still have bunch of other mods to use and figure out how THEY work. Still agreeing on the removal of Modular Powersuit until further fixes.

**Comment by The-1-7-10-Pack** [comment] 2015-02-19 19:18
@joelou1 2 very powerful sets of armor are included on the quest book, you should check them out :wink:

**Comment by joelou1** [comment] 2015-02-19 19:27
Speaking of which, I've got a few questions regarding it. Shall I make another Post/Issue?

**Comment by The-1-7-10-Pack** [comment] 2015-02-20 10:50
Yes.

**Comment by Korynkai** [comment] 2015-02-21 19:28
Yep, this is being addressed in the upcoming release (0.11.0.7-QMX)... And yes, this isn't a modpack issue (#don't_blame_the_modpack is definitely a proper label for this issue... Really blame me for a slight goof with the recipe handler... :pensive:). To report issues for the QMX branch of MPS, please use http://bugzilla.qmxtech.com.

To see the currenty open bug list for 0.11.0.7-QMX, please look at http://goo.gl/6ex25s. The list of all bugs addressed in 0.11.0.7-QMX is here: http://goo.gl/ZdBwrU.

**Closed** 2015-02-25 12:21 UTC
Labels: #don't_blame_the_modpack, bug
