### ISSUE TITLE
Can't Successfully connect to a pre-generated world file on multiplayer :(

### ISSUE THREAD

**Issue by ZuneGamer** [The-1-7-10-Pack/The-1.7.10-Pack#442] opened 2015-04-02 00:44 UTC
Ok, I've gotten the server to successfully get to 10/19 applied (whatever that means) and it wont go any further.  I crash every time I try to connect to it, as well. Could someone please clarify things for me?  I'm still new to the preceding 1.6.4 servers (let alone modded ones).  The first image is the 10/19 thing I mentioned.  The second, third, fourth, and fifth images are of the error message I get when I try and join.
![capture0](https://cloud.githubusercontent.com/assets/11763391/6956833/9548d652-d8a8-11e4-8fa5-9331c77ef440.PNG)
![capture0](https://cloud.githubusercontent.com/assets/11763391/6957773/ff6937ea-d8b5-11e4-93f0-954bd665d5b2.PNG)
![capture0](https://cloud.githubusercontent.com/assets/11763391/6957784/2f6b296c-d8b6-11e4-9d01-270502beee20.PNG)
![capture0](https://cloud.githubusercontent.com/assets/11763391/6957793/6db194b8-d8b6-11e4-8621-c5c69d2ab8bc.PNG)
![capture0](https://cloud.githubusercontent.com/assets/11763391/6957802/962b74a4-d8b6-11e4-934a-2734f1a7be2a.PNG)

**Comment by ZuneGamer** [comment] 2015-04-02 00:47
![capture0](https://cloud.githubusercontent.com/assets/11763391/6955710/1fa832fa-d897-11e4-9474-986cd7654e2c.PNG)

**Comment by ZuneGamer** [comment] 2015-04-02 00:55
Nvm im a n00b, it seems.
I didn't agree to the eula >.<

**Comment by ZuneGamer** [comment] 2015-04-02 02:52
Ok, I've gotten the server to successfully get to 11/19 applied (whatever that means) and it wont go any higher.  I crash every time I try to connect to it, as well. Could someone please clarify things for me?  I'm still new to the 1.6.4+ server making (let alone modded servers)
![capture0](https://cloud.githubusercontent.com/assets/11763391/6956833/9548d652-d8a8-11e4-8fa5-9331c77ef440.PNG)

**Comment by CriticalRocket** [comment] 2015-04-02 07:12
Well, first of all. To copy test from the CMD: Right mouse click -> Select all -> Press enter on your keyboard. Then it's copied to your clipboard ;) Next you can upload the text to pastebin or something like that and post the link here, makes stuff much easier. 

10/19 applied is as far as it goes. After it says 'unloaded dimension 1' you're good to go :)
So don't worry about that.

As far as your actual problem, I don't know what is causing the NetworkDispatcher Error you're getting. Could you go to your server folder 0> Crash reports folder and post the latest crash report?

**Comment by CriticalRocket** [comment] 2015-04-02 07:47
Oke, I'm having server problems myself, and it seems I'm having exactly the same problem.
My client crashed on trying to join, making me think it is a client side error. But I tried using a fresh world on my server and I didn't get the crash.
Conclusion: The world is making my client crash. How great.

Crash report client:
http://pastebin.com/ftDUSmrW

Heyitsme/Jon: Maybe you should close my thread and we'll continue discussing this here :)

**Comment by ZuneGamer** [comment] 2015-04-02 08:13
Yes I am trying to use my own singleplayer world as well, I have not tried running a new one I'll do that and tell you guys what happens tomorrow, night

**Comment by CriticalRocket** [comment] 2015-04-02 14:34
I did, yes.

**Comment by CriticalRocket** [comment] 2015-04-02 14:37
I was on v0.7.6a, then I crashed all the time yesterday so I switched to 0.7.5 to see if that'd help, but now today I tried 0.7.6a again, and I got a different error. I'm getting the ticking block entity thing now, which I'm going to try to fix by removing all the blocks that are causing it (openblocks -> goldenegg).

But first I'm going to see if I can turn just the one block completely, or if removing the mod entirely helps.

**Comment by The-1-7-10-Pack** [comment] 2015-04-02 17:57
@CriticalRocket Okay, update me.

**Comment by CriticalRocket** [comment] 2015-04-02 20:00
I tried disabling the block in the config, but I still crashed, Going to try the world in SSP v0.76a next, then going to try disabling the mod (server) totally see if that helps.

**Comment by CriticalRocket** [comment] 2015-04-02 20:19
Wth.. loading my SMP world into SSP gives me the error "Cannot Hotload Dim: Overworld is not Loaded!". o.O
http://pastebin.com/Y6RfEy24

**Comment by CriticalRocket** [comment] 2015-04-02 21:05
I tried disabling the mod, and whilst loading the server the cmd gave me a list of all the blocks it was missing, GoldenEgg wasn't in there.
I couldn't join however, my client crashed again.

I got a different crash log, without anything about the GoldenEgg:
http://pastebin.com/PYMyPFXe

I'm getting "NoClassDefFoundError: net/minecraft/world/World$2".
Some googling got me this:
http://www.minecraftforge.net/forum/index.php?topic=23468.0

So this line in the crash report makes me thing SlimeGrass is causing problems:
"at tconstruct.blocks.slime.SlimeGrass.func_149674_a(SlimeGrass.java:106)"

I can't find anything about 'SlimeGrass' in any config. 

I really dont want to remove Tinkers Construct ><  I'll try that though just to test if it fixes the problem.

**Comment by CriticalRocket** [comment] 2015-04-02 21:09
Found this:

https://github.com/MinecraftForge/FML/issues/483

Latest post:
"As this issue is the first github issue when googling this error, I just want to leave the solution for when I hit this problem, as it might help others.
This exception seems to happen if you manage to create an infinite loop of notifyBlockOfNeighborChange. (I.e, one block being updated causes it to update the original block etc.).
It seems to fall back to the original call to notifyBlockOfNeighborChange and throw a java.lang.NoClassDefFoundError: net/minecraft/world/World$2."

This doesn't help me fix this though, as I already knew that a block was causing the problem. I don't see how knowing how its causing the problem is going to help. Correct me if I'm wrong, but the only solution I see is removing the faulty block.

**Comment by ZuneGamer** [comment] 2015-04-02 21:33
No, I have not run the singleplayer world in 0.7.6a, I ran it with just 0.7.6, but quickly reverted as soon as a crashed the first time.  I used a backup file, so technically, I have not run the save file with any other version than 0.7.5.  Got the server to work, when it generated a new world.  Just can't get it to run the singleplayer save.

**Comment by The-1-7-10-Pack** [comment] 2015-04-02 22:17
@CriticalRocket Do you have any backup? reverting saves from mod updates is problematic because they don't put effort for it to work, they invest more on updating to newer versions.

**Comment by CriticalRocket** [comment] 2015-04-03 13:04
I do have a few backups, but the most recent one is from 1 or 2 days before the incident, and I did lots of work on the server in those 1/2 days xd

I'm going to try and fix the world, and if all else fails, load a backup. My playerdata from my uptodate map should be OK though, so thats something..

Also, the backup mod doesn't have an option to save certain backups for longer periods. I've got it on 1 backup every thirty minute and to keep 5 or something. But because my client was crashing most of the time, and not my server, it wrote over my older backups, so now I've only got backups with the crash in it, if you understand what I'm saying.

What would be perfect:

-The first backup of the day will be kept for x (configurable) hours/days.
-All other backups that day will be kept for x hours/days, or will be overwritten when the 
maximum number of backups is reached.
The first backup, however, doesn't count towards this minimum number and is always kept for the set amount of hours/days

That way you'll always have a backup of 1 day before the crash, without the risk of it being overwritten whilst starting the server, if you know what I mean.

I know I should've made a backup of my backup when I crashed. But I'm just saying that the main point of a backup mod is to automate backups.. Still, the mod isnt useless. But I'm just wondering if there isn't a better backup mod out there.

**Comment by The-1-7-10-Pack** [comment] 2015-04-04 20:20
Well, there's nothing I can do for now guys. If there's anything new update me, but problematic game saves happen in Minecraft all the time.
Closing it for now, I'll reopen if anything new will happen.

**Closed by The-1-7-10-Pack** 2015-04-04 20:20 UTC
Labels: help wanted

**Comment by CriticalRocket** [comment] 2015-04-05 20:02
Can I still post stuff here?

**Comment by The-1-7-10-Pack** [comment] 2015-04-05 20:16
Great :)

**Comment by CriticalRocket** [comment] 2015-04-05 20:37
Hmm, small problem.

99% of my chests are empty, and the ones that aren't don't have the correct items in them. Theyve got the items from the old save file I imported the level.dat files to.

Also, when I walk around in my house, when I pass a certain X coordinate about 10 of my chests become see-through. 

The problem is probably that the chests are there in the level.dat files but they arent in the region files or smthing. The chests that do have items are chests that I haven't changed. I only changed the contents. the other chests used to be mostly wooden which I later changed to iron and gold.

Question is: Do you know where I can find the location of the file which holds chest information? If I can acces that I can just copy the info from my most recent (not working) save to my now working save :)


p.s. also some random groups of blocks have spawned (f.e. about 30 alloy smelters in my factory where there used to be air), and some blocks are gone. More weird stuff like that. But thats not a big deal, easy to fix. Chest contents are more of a pain :p

**Comment by CriticalRocket** [comment] 2015-04-05 20:53
P.s. can you pin threads to always show up on top? Because if so, I'd like to create a little tutorial on how to report problems here.. almost nobody posts enough information in their first post and it's really annoying me xd.

**Comment by The-1-7-10-Pack** [comment] 2015-04-05 21:03
I can not, but there's [this](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md) readme file :)

**Comment by CriticalRocket** [comment] 2015-04-05 21:05
Haha oke xD
